### PR TITLE
Make chat bubbles align left and right without having to use text-align

### PR DESCRIPTION
**Pull request by hmottestad**
Screenshot 2023-08-26 at 23 22 50

 - keep whitespace in user message
 - align the user chat bubble to the right using flex box and margins, this also allows the "Thanks" message to be smaller than the other messages
 - align the ai chat bubble to the left similarly to how the user chat bubble is aligned to the right

### CODE REVIEW

**Comment by hmottestad** [comment]
@rtcfirefly @gmelsby

**Comment by rtcfirefly** [comment]
Hi! Looks good, just need to test it on my side then I can merge

**Comment by rtcfirefly** [comment]
Hi @hmottestad, 

This change causes a small issue with the copy button when the response text is short
Screenshot 2023-08-28 at 1 11 55 PM

**Comment by hmottestad** [comment]
Thanks for looking into my PR @rtcfirefly. I'm not able to do more work on the PR at the moment. You can close it if you want.

**Comment by rtcfirefly** [comment]
No worries, I'll see if I can find time to fix it. Thanks for the contribution!

**Comment by rtcfirefly** [comment]
Hey @hmottestad, I just merged this. I wasn't able to repro my previous issue.

Thanks again!

**Pull request merged**
